Create and style the tm
LeTranAnhVu/calender-lib pull request #2
Opened 2022-12-21 20:42 UTC by tramtran0497

2022-12-25 17:36 UTC, LeTranAnhVu requested changes
- Update main branch to this PR
- Check eslint and prettier

2022-12-25 17:36 UTC, LeTranAnhVu commented on src/layout/components/CalendarDay/TimeFrameOverlay.tsx
> +    const numberOfLines = Math.round((height - 24)/24)
- What is 24? 
- If the logic is not clear, please add some comment above it.
- I thin we can use `useMemo` in this case

2022-12-25 17:36 UTC, LeTranAnhVu commented on src/layout/components/CalendarDay/TimeFrameOverlay.scss
> +.time-frame-overlay-wrapper {
Clean all unused comment codes in this file and also check all changed files the PR

2022-12-25 17:36 UTC, LeTranAnhVu commented on src/lib/__tests__/timeToHeightPx.test.ts
> +    })
You can make it shorter in this case by using `test.each` . Check out the example in here : https://dev.to/bgord/simplify-repetitive-jest-test-cases-with-test-each-310m

2022-12-25 17:36 UTC, LeTranAnhVu commented on src/layout/components/CalendarDay/TimeFrameOverlay.scss
> +    height: 47px; // default height for 1 hour
```suggestion
```
Useless code, remove it

2022-12-25 17:36 UTC, LeTranAnhVu commented on src/layout/components/CalendarDay/TimeFrameOverlay.scss
> +    margin: 1px 0px;
```suggestion
```

2022-12-25 17:36 UTC, LeTranAnhVu commented on src/layout/components/CalendarDay/TimeFrameOverlay.scss
> +        display: -webkit-box;
Should add some comment to explain the style, better for reviewing it later

2022-12-25 17:36 UTC, LeTranAnhVu commented on src/layout/components/CalendarDay/TimeFrameOverlay.scss
> +        font-size: 11px;
Use `em`

2022-12-25 17:36 UTC, LeTranAnhVu commented on src/layout/components/CalendarDay/TimeFrameOverlay.scss
> +        font-size: 11px;
Around 0.8 or 0.9 `em`

2022-12-26 13:12 UTC, tramtran0497 commented on src/layout/components/CalendarDay/TimeFrameOverlay.tsx
> +    const numberOfLines = Math.round((height - 24)/24)
- 24 is line-height

2022-12-26 15:49 UTC, merged